dist/webdnn.d.ts
dist/webdnn.es5.d.ts
src/graph_transpiler/webdnn/backend/code_generator/allocator.py

When `OPTIMIZE=0`, allocator didn't allocate constant buffers sequentially.

fix allocation bug

---

src/graph_transpiler/webdnn/backend/code_generator/allocator.py

#264
```shell
#before
$ time python convert_resnet_chainer.py --backend webgpu
real	0m16.241s
user	0m14.828s
sys	0m1.120s
#after
$ time python convert_resnet_chainer.py --backend webgpu
real	0m7.496s
user	0m6.481s
sys	0m1.038s
```

improve allocation algorithm

---

example/mnist/README.md
example/mnist/descriptor_run_mnist.es5.html
example/mnist/descriptor_run_mnist.html
example/mnist/train_mnist_pytorch.py
src/graph_transpiler/webdnn/graph/converters/converter.py
src/graph_transpiler/webdnn/graph/converters/pytorch.py

This is experimental implementation and only few functions in pytorch is supported.

add pytorch converter

---

bin/convert_caffe.py
bin/convert_keras.py
example/convert_neural_style_transfer/convert.py
example/convert_neural_style_transfer/model.py
example/mnist/train_mnist_chainer.py
example/resnet/convert_resnet_chainer.py
src/graph_transpiler/webdnn/graph/converters/chainer.py
src/graph_transpiler/webdnn/graph/converters/converter.py
src/graph_transpiler/webdnn/graph/converters/keras.py

Keras abstract

---

src/graph_transpiler/webdnn/frontend/keras/converter.py
src/graph_transpiler/webdnn/frontend/keras/layers/core.py
test/runtime/frontend_test/keras_test/layers_test/core_test/repeat_vector_test.py
test/runtime/frontend_test/keras_test/layers_test/core_test/reshape_test.py

- `keras.layers.RepeatVector`
- `keras.layers.Reshape`
- runtime tests

add converter handlers for keras layers

---

bin/convert_keras.py

モデルがカスタムレイヤーを使っている場合、プラグインでカスタムレイヤーとそのコンバータハンドラを定義するだけでは、load_modelが失敗します。
これを解決するために、load_modelにカスタムレイヤーの情報を渡すように修正しました。
(Kerasを十分理解していないので汎用性に欠ける部分があるかもしれません。レビューよろしくお願い致します。)
ご協力ありがとうございました。

load_model needs custom_objects to load custom layers

---

bin/convert_keras.py

support multiple input variable and bugfix

---

src/graph_transpiler/webdnn/backend/webassembly/kernels/__init__.py
src/graph_transpiler/webdnn/backend/webassembly/kernels/depth2space.py
src/graph_transpiler/webdnn/backend/webgpu/kernels/__init__.py
src/graph_transpiler/webdnn/backend/webgpu/kernels/depth2space.py
src/graph_transpiler/webdnn/frontend/chainer/functions/array.py
src/graph_transpiler/webdnn/graph/operators/__init__.py
src/graph_transpiler/webdnn/graph/operators/depth2space.py

I implement Chainer's `F.depth2space` in this PR. Function `F.depth2space` is designed to compute subpixel CNN for feature map upscaling.  (Refer https://arxiv.org/abs/1609.05158 for the detail.)

Implement F.depth2space for Chainer 

---

setup.py

raise error when python < 3.6

---

src/graph_transpiler/webdnn/frontend/keras/layers/pooling.py
src/graph_transpiler/webdnn/graph/operators/pooling_2d.py
test/runtime/frontend_test/keras_test/layers_test/pooling_test/average_pooling_1d_test.py
test/runtime/frontend_test/keras_test/layers_test/pooling_test/average_pooling_2d_test.py
test/runtime/frontend_test/keras_test/layers_test/pooling_test/max_pooling_2d_test.py

avoid corner case in test and show warning in converter in such case

---

CONTRIBUTING.md
LICENSE.txt
README_ja.md
test/README.md

Contribution guide

---

bin/convert_keras.py

In order to avoid missing loss function which are used for training

convert_keras with compile=False 

---

.circleci/config.yml

update ci configuration

---

docs/source/tips/build_js.md
docs/source/tips/index.md

add doc of how to build js

---

src/graph_transpiler/webdnn/backend/webgpu/generator.py

use 'command' instead of 'type' to check command existence

---

src/graph_transpiler/webdnn/frontend/chainer/converter.py
src/graph_transpiler/webdnn/frontend/chainer/functions/normalization.py
test/runtime/frontend_test/chainer_test/batch_normalization_test.py

- Fix compatibility for chainer v1.24
- Fix the bug about traverse operation

#478 fix chainer frontend compatibility

---

src/graph_transpiler/webdnn/graph/operators/elementwise.py

preserve data order of the variable of largest number of dimensions

---

example/mnist/train_mnist_chainer.py

fix when chainer model is on GPU

---

src/graph_transpiler/webdnn/backend/webgpu/kernels/tanh.py

avoid NaN of tanh in fast math mode

---

src/graph_transpiler/webdnn/backend/webgpu/kernels/sigmoid.py
test/runtime/operators_test/sigmoid_test.py

avoid sigmoid overflow

---

src/graph_transpiler/webdnn/graph/node.py
src/graph_transpiler/webdnn/graph/traverse.py
test/webdnn_test/graph_test/traverse_test.py

Update listup_nodes algorithm to skip internal input/output nodes

---

src/graph_transpiler/webdnn/optimizer/general_optimize_rule.py
src/graph_transpiler/webdnn/optimizer/sub_rules/upgrade_operator_type.py
src/graph_transpiler/webdnn/util/flags/__init__.py
test/webdnn_test/optimizer_test/sub_rules_test/upgrade_operator_type_test.py

automatically update deprecated operators to admired one.

add UpgradeOperatorType optimize rule

---

bin/convert_keras.py

#631 fix placeholder duplication

---

src/graph_transpiler/webdnn/backend/webassembly/kernels/__init__.py
src/graph_transpiler/webdnn/backend/webassembly/kernels/slice.py
src/graph_transpiler/webdnn/backend/webgl/kernels/__init__.py
src/graph_transpiler/webdnn/backend/webgl/kernels/slice.py
src/graph_transpiler/webdnn/backend/webgl/kernels/util.py
src/graph_transpiler/webdnn/backend/webgpu/kernels/__init__.py
src/graph_transpiler/webdnn/backend/webgpu/kernels/slice.py
src/graph_transpiler/webdnn/frontend/chainer/functions/array.py
src/graph_transpiler/webdnn/frontend/keras/layers/convolutional.py
src/graph_transpiler/webdnn/frontend/keras/layers/pooling.py
src/graph_transpiler/webdnn/frontend/keras/layers/util.py
src/graph_transpiler/webdnn/frontend/tensorflow/ops/gen_array_ops.py
src/graph_transpiler/webdnn/graph/axis.py
src/graph_transpiler/webdnn/graph/operators/__init__.py
src/graph_transpiler/webdnn/graph/operators/slice.py
src/graph_transpiler/webdnn/graph/variable.py
test/runtime/frontend_test/chainer_test/functions_test/array_test/get_item_test.py
test/runtime/frontend_test/tensorflow_test/ops_test/gen_array_ops_test/slice_test.py
test/runtime/frontend_test/tensorflow_test/ops_test/gen_array_ops_test/strided_slice_test.py
test/runtime/operators_test/slice_test.py

Support slice operation like follows:
```python
x = Variable([2,3,4,5], OrderNHWC)
y = x[:, None, 3, ...]
```
`tf.Tensor.__getitem__` and `chainer.Variable.__getitem__` is also supported.

Support slice operation

---

src/graph_transpiler/webdnn/backend/webgl/kernels/slice.py
src/graph_transpiler/webdnn/frontend/keras/layers/convolutional.py
src/graph_transpiler/webdnn/frontend/keras/layers/pooling.py
src/graph_transpiler/webdnn/frontend/keras/layers/util.py
src/graph_transpiler/webdnn/graph/operators/slice.py
test/runtime/frontend_test/keras_test/layers_test/convolutional_test/conv2d_test.py
test/runtime/frontend_test/keras_test/layers_test/convolutional_test/conv2d_transpose_test.py
test/runtime/frontend_test/keras_test/layers_test/convolutional_test/separable_conv2d_test.py

#639 
Support `keras.layers.SeparableConv2D`.

 support SeparableConv2D in Keras

---

src/graph_transpiler/webdnn/frontend/chainer/converter.py
src/graph_transpiler/webdnn/frontend/keras/converter.py
src/graph_transpiler/webdnn/frontend/pytorch/converter.py
src/graph_transpiler/webdnn/frontend/tensorflow/converter.py
src/graph_transpiler/webdnn/frontend/util.py

Current version check algorithm is very ugly and sometimes it's wrong.
```python
>>> "2.10.0" < "2.2.0"
True
```

fix version check algorithm

---

src/graph_transpiler/webdnn/frontend/tensorflow/ops/gen_array_ops.py
src/graph_transpiler/webdnn/graph/operators/convolution2d.py
src/graph_transpiler/webdnn/graph/operators/deconvolution2d.py
src/graph_transpiler/webdnn/graph/operators/pooling_2d.py
src/graph_transpiler/webdnn/graph/operators/reshape.py
src/graph_transpiler/webdnn/util/assertion.py
src/graph_transpiler/webdnn/util/flags/__init__.py
test/webdnn_test/util_test/assertion_test.py

Assert element type of sequence parameter

---

src/graph_transpiler/webdnn/frontend/chainer/functions/basic_math.py
src/graph_transpiler/webdnn/frontend/chainer/functions/pooling.py
src/graph_transpiler/webdnn/frontend/chainer/placeholder_variable.py
src/graph_transpiler/webdnn/frontend/keras/layers/convolutional.py
src/graph_transpiler/webdnn/frontend/keras/layers/embeddings.py
src/graph_transpiler/webdnn/frontend/keras/layers/merge.py
src/graph_transpiler/webdnn/frontend/keras/layers/pooling.py
src/graph_transpiler/webdnn/frontend/keras/layers/util.py
src/graph_transpiler/webdnn/frontend/onnx/defs/util.py
src/graph_transpiler/webdnn/frontend/tensorflow/ops/gen_image_ops.py
src/graph_transpiler/webdnn/frontend/tensorflow/ops/gen_math_ops.py
src/graph_transpiler/webdnn/frontend/tensorflow/ops/gen_nn_ops.py
src/graph_transpiler/webdnn/frontend/tensorflow/util.py
src/graph_transpiler/webdnn/graph/operators/average_pooling_2d.py
src/graph_transpiler/webdnn/graph/operators/max_pooling_2d.py
src/graph_transpiler/webdnn/graph/operators/pooling_2d.py
test/runtime/frontend_test/chainer_test/functions_test/pooling_test/average_pooling_2d_test.py
test/runtime/frontend_test/chainer_test/functions_test/pooling_test/max_pooling_2d_test.py
test/runtime/frontend_test/keras_test/layers_test/pooling_test/average_pooling_2d_test.py
test/runtime/frontend_test/keras_test/layers_test/pooling_test/max_pooling_2d_test.py

support uneven size padding

---

src/graph_transpiler/webdnn/frontend/chainer/functions/normalization.py

support general BN function in Chainer

---

example/benchmark/convert.sh
example/benchmark2/convert.sh

Modified `example/benchmark/convert.sh` and `example/benchmark2/convert.sh` by changing `python` to `python3`, correcting git command with "git reset". 
@Kiikurage please help review this PR, thanks

Fixed two scripts' issues

---

example/benchmark/convert.sh
example/benchmark/requirements.txt

Fixed #714 
@Kiikurage please help review this PR, thanks

Fixed convert.sh missed dependency packages

---

docs/source/tutorial/setup.md

Fix doc issue #718 
@Kiikurage PTAL

[doc] fix issue #718

---

example/benchmark/convert.sh

Fix #724 #725

---

README.md
requirements/dev.txt

keras support version change due to its internal structure change

---

dist/webdnn.es5.js
package-lock.json

'chjj / marked' < 0.3.9 have vulnerability

update package dependency for avoiding security vulnerability in 

---

example/benchmark/convert.sh
example/benchmark/generate_keras_models.py

#732 generate keras model h5 file separately to keep input tensor name as 'input_1'.

fix benchmark script bug

---

.npmignore
package-lock.json
package.json

Ready for npm publish.
Version updated to 1.2.0 for indicating changes from 1.1.0.

NPM package

---

.circleci/config.yml

change the process of building documents

fix CI configuration

---

src/graph_transpiler/webdnn/backend/fallback/kernels/average_pooling_2d.py
src/graph_transpiler/webdnn/backend/webassembly/kernels/average_pooling_2d.py
src/graph_transpiler/webdnn/backend/webgl/kernels/average_pooling_2d.py
src/graph_transpiler/webdnn/backend/webgpu/kernels/average_pooling_2d.py
src/graph_transpiler/webdnn/frontend/keras/layers/pooling.py
src/graph_transpiler/webdnn/graph/operators/average_pooling_2d.py
test/runtime/frontend_test/keras_test/layers_test/pooling_test/average_pooling_2d_test.py

support tensorflow style padding handling in average pooling #694, #786

---

README.md
README_ja.md
src/graph_transpiler/webdnn/frontend/chainer/converter.py
src/graph_transpiler/webdnn/frontend/chainer/functions/array.py

I tested current code with Chainer 4.0.0.
On MNIST and ResNet example, there was no problem.

change supported chainer version to v4

---

example/transform_url/README.md
example/transform_url/index.html
example/transform_url/script.js
src/descriptor_runner/descriptor_runner/descriptor_runner_webassembly.ts
src/graph_transpiler/webdnn/backend/webassembly/webassembly_header.js

Apply transformUrlDelegate to wasm file

---

src/graph_transpiler/webdnn/backend/webgl/optimize_rules/unroll_concat.py
test/runtime/operators_test/concat_test.py

fix unroll_concat when the number of input is odd

---

README.md
README_ja.md

update AZ.js link

---

README.md

This is an application of real time emotion recognition with webdnn.
Here www.morphcast.com you can find other applications, at the moment fruit recognition example in introduction video uses webdnn and we have also other face related models ready to launch in our AI SDK.

Link to emotion recognition application

---

example/resnet/README.md
example/resnet/convert_resnet_pytorch.py
example/resnet/index.es5.html
example/resnet/index.html
example/resnet/script.es5.js
example/resnet/script.js
src/graph_transpiler/webdnn/frontend/onnx/converter.py
src/graph_transpiler/webdnn/frontend/onnx/defs/generator.py
src/graph_transpiler/webdnn/frontend/onnx/defs/tensor.py
test/runtime/frontend_test/onnx_test/defs_test/tensor_test/unsqueeze_test.py
test/runtime/frontend_test/onnx_test/util.py

Supports latest pytorch's alexnet model.

Latest pytorch

---

example/mnist/train_mnist_chainer.py
example/mnist/train_mnist_keras.py
example/mnist/train_mnist_pytorch.py
example/mnist/train_mnist_tensorflow.py
example/resnet/convert_resnet_chainer.py
example/resnet/convert_resnet_keras.py
example/resnet/convert_resnet_pytorch.py
example/resnet/convert_resnet_tensorflow.py
src/graph_transpiler/webdnn/backend/__init__.py
src/graph_transpiler/webdnn/backend/interface/generator.py
src/graph_transpiler/webdnn/frontend/onnx/defs/nn.py
src/graph_transpiler/webdnn/util/flags/__init__.py
test/runtime/frontend_test/onnx_test/defs_test/nn_test/batch_normalization_test.py

Closes #897, closes #898, closes #893

Onnx batchnorm

---

bin/convert_caffe.py

fix bn issue in caffe

---

README.md

Yahoo open-nsfw converted and ready to use with WebDNN

Add OpenNSFW demo to README

---

src/descriptor_runner/backend/webgl/pack.ts
src/descriptor_runner/backend/webgl/webglContextImpl.ts
src/descriptor_runner/backend/webgl/webglTensorImpl.ts
test/model_test/make_models.py
test/model_test/runner/optimized.html
test/model_test/runner/standard.html
test/model_test/runner/test.js

Ios15 webgl
